#
#    Copyright (c) 2021 OpenCFLite Authors. All Rights Reserved.
#
#    This file contains Original Code and/or Modifications of Original Code
#    as defined in and that are subject to the Apple Public Source License
#    Version 2.0 (the 'License'). You may not use this file except in
#    compliance with the License. Please obtain a copy of the License at
#    http://www.opensource.apple.com/apsl/ and read it before using this
#    file.
#
#    The Original Code and all software distributed under the License are
#    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
#    EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
#    INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
#    Please see the License for the specific language governing rights and
#    limitations under the License.
#

#
#    Description:
#      This file is the GitHub Actions hosted, distributed continuous
#      integration configuration file for OpenCFLite.
#

name: Build

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    name: "Linux ${{matrix.compiler['name']}}"
    strategy:
      matrix:
        compiler:
          - { name: GCC,        c: gcc,   cxx: g++ }
          - { name: clang/LLVM, c: clang, cxx: clang++ }
    env:
      CC: ${{matrix.compiler['c']}}
      CXX: ${{matrix.compiler['cxx']}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Package Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install autoconf automake libtool
        sudo apt-get -y install gobjc gobjc++ uuid-dev libicu-dev
    - name: Install Distribution Archive Dependencies
      run: |
        cd /tmp
        curl https://data.iana.org/time-zones/releases/tzcode2021a.tar.gz -o tzcode2021a.tar.gz || wget https://data.iana.org/time-zones/releases/tzcode2021a.tar.gz
        mkdir tzcode2021a
        tar --directory tzcode2021a -zxf tzcode2021a.tar.gz
    - name: Configure
      run: |
        ./configure -C --with-tz-includes=/tmp/tzcode2021a
    - name: Build
      run: |
        make -j
    - name: Test
      run: |
        make -j distcheck
